// <auto-generated />
using System;
using CPS.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CPS.API.Migrations
{
    [DbContext(typeof(CpsDbContext))]
    [Migration("20260417001203_ChangeClientMasterUniqueKeyToRCMSCode")]
    partial class ChangeClientMasterUniqueKeyToRCMSCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CPS.API.Models.AppSetting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingID");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("CPS.API.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CPS.API.Models.Batch", b =>
                {
                    b.Property<long>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BatchID"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("BatchDate")
                        .HasColumnType("date");

                    b.Property<int>("BatchStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int?>("RRLockedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RRLockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ScanLockedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScanLockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ScannerMappingID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(15,3)");

                    b.Property<int>("TotalSlips")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("BatchID");

                    b.HasIndex("BatchNo")
                        .IsUnique();

                    b.HasIndex("BatchStatus");

                    b.HasIndex("LocationID", "BatchDate");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("CPS.API.Models.BatchSequence", b =>
                {
                    b.Property<int>("SeqID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeqID"));

                    b.Property<DateOnly>("BatchDate")
                        .HasColumnType("date");

                    b.Property<int>("LastSeqNo")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int?>("ScannerMappingID")
                        .HasColumnType("int");

                    b.HasKey("SeqID");

                    b.HasIndex("LocationID");

                    b.HasIndex("ScannerMappingID");

                    b.HasIndex("BatchDate", "LocationID", "ScannerMappingID")
                        .IsUnique()
                        .HasFilter("[ScannerMappingID] IS NOT NULL");

                    b.ToTable("BatchSequences");
                });

            modelBuilder.Entity("CPS.API.Models.ClientMaster", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PickupPointCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupPointDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RCMSCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StatusDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ClientID");

                    b.HasIndex("CityCode");

                    b.HasIndex("RCMSCode")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CPS.API.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<string>("ClusterCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Grid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIFPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.HasIndex("LocationCode")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CPS.API.Models.LocationFinance", b =>
                {
                    b.Property<int>("FinanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinanceID"));

                    b.Property<string>("BOFD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DepositAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("IFSC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("PreTrun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("FinanceID");

                    b.HasIndex("LocationID")
                        .IsUnique();

                    b.ToTable("LocationFinances");
                });

            modelBuilder.Entity("CPS.API.Models.LocationScanner", b =>
                {
                    b.Property<int>("ScannerMappingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScannerMappingID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("ScannerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScannerModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScannerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ScannerMappingID");

                    b.HasIndex("LocationID");

                    b.ToTable("LocationScanners");
                });

            modelBuilder.Entity("CPS.API.Models.MasterUploadLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuccessRows")
                        .HasColumnType("int");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.ToTable("MasterUploadLogs");
                });

            modelBuilder.Entity("CPS.API.Models.ScanItem", b =>
                {
                    b.Property<int>("ScanItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScanItemID"));

                    b.Property<long>("BatchID")
                        .HasColumnType("bigint");

                    b.Property<string>("ChqAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChqDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChqNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSlip")
                        .HasColumnType("bit");

                    b.Property<string>("MICR1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MICR2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RRState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScanIndex")
                        .HasColumnType("int");

                    b.Property<string>("ScanStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.Property<int?>("SlipID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ScanItemID");

                    b.HasIndex("BatchID");

                    b.HasIndex("SlipID");

                    b.HasIndex("BatchID", "SeqNo");

                    b.ToTable("ScanItems");
                });

            modelBuilder.Entity("CPS.API.Models.Slip", b =>
                {
                    b.Property<int>("SlipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlipID"));

                    b.Property<long>("BatchID")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DepositSlipNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PickupPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SlipAmount")
                        .HasColumnType("decimal(15,3)");

                    b.Property<int>("SlipStatus")
                        .HasColumnType("int");

                    b.Property<string>("SlipNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalInstruments")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("SlipID");

                    b.HasIndex("BatchID");

                    b.HasIndex("BatchID", "SlipNo")
                        .IsUnique();

                    b.ToTable("Slips");
                });

            modelBuilder.Entity("CPS.API.Models.SlipSequence", b =>
                {
                    b.Property<int>("SeqID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeqID"));

                    b.Property<int>("LastSeqNo")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int?>("ScannerMappingID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SlipDate")
                        .HasColumnType("date");

                    b.HasKey("SeqID");

                    b.HasIndex("LocationID");

                    b.HasIndex("ScannerMappingID");

                    b.HasIndex("SlipDate", "LocationID", "ScannerMappingID")
                        .IsUnique()
                        .HasFilter("[ScannerMappingID] IS NOT NULL");

                    b.ToTable("SlipSequences");
                });

            modelBuilder.Entity("CPS.API.Models.UserLocationHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("HistoryID");

                    b.HasIndex("UserID", "AssignedDate");

                    b.ToTable("UserLocationHistories");
                });

            modelBuilder.Entity("CPS.API.Models.UserMaster", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("bit");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleChecker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleMaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleScanner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SessionTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserID");

                    b.HasIndex("EmployeeID")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CPS.API.Models.Batch", b =>
                {
                    b.HasOne("CPS.API.Models.Location", "Location")
                        .WithMany("Batches")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPS.API.Models.LocationScanner", "ScannerMapping")
                        .WithMany()
                        .HasForeignKey("ScannerMappingID");

                    b.Navigation("Location");

                    b.Navigation("ScannerMapping");
                });

            modelBuilder.Entity("CPS.API.Models.BatchSequence", b =>
                {
                    b.HasOne("CPS.API.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPS.API.Models.LocationScanner", "ScannerMapping")
                        .WithMany()
                        .HasForeignKey("ScannerMappingID");

                    b.Navigation("Location");

                    b.Navigation("ScannerMapping");
                });

            modelBuilder.Entity("CPS.API.Models.LocationFinance", b =>
                {
                    b.HasOne("CPS.API.Models.Location", "Location")
                        .WithOne("Finance")
                        .HasForeignKey("CPS.API.Models.LocationFinance", "LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CPS.API.Models.LocationScanner", b =>
                {
                    b.HasOne("CPS.API.Models.Location", "Location")
                        .WithMany("Scanners")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CPS.API.Models.ScanItem", b =>
                {
                    b.HasOne("CPS.API.Models.Batch", "Batch")
                        .WithMany("ScanItems")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPS.API.Models.Slip", "Slip")
                        .WithMany("ScanItems")
                        .HasForeignKey("SlipID");

                    b.Navigation("Batch");

                    b.Navigation("Slip");
                });

            modelBuilder.Entity("CPS.API.Models.Slip", b =>
                {
                    b.HasOne("CPS.API.Models.Batch", "Batch")
                        .WithMany("Slips")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("CPS.API.Models.SlipSequence", b =>
                {
                    b.HasOne("CPS.API.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPS.API.Models.LocationScanner", "ScannerMapping")
                        .WithMany()
                        .HasForeignKey("ScannerMappingID");

                    b.Navigation("Location");

                    b.Navigation("ScannerMapping");
                });

            modelBuilder.Entity("CPS.API.Models.Batch", b =>
                {
                    b.Navigation("ScanItems");

                    b.Navigation("Slips");
                });

            modelBuilder.Entity("CPS.API.Models.Location", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Finance");

                    b.Navigation("Scanners");
                });

            modelBuilder.Entity("CPS.API.Models.Slip", b =>
                {
                    b.Navigation("ScanItems");
                });

#pragma warning restore 612, 618
        }
    }
}
